Update on main.yaml

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -25,8 +25,18 @@ jobs:
     with:
       flutter_channel: stable
       setup: |
-        echo "$GOOGLE_SERVICE_PROD"
-        echo "$FIREBASE_KEYS_PROD"
+        if [ -n "$GOOGLE_SERVICE_PROD" ]; then
+          echo "GOOGLE_SERVICE_PROD is set."
+        else
+          echo "Error: GOOGLE_SERVICE_PROD is not set." >&2
+          exit 1
+        fi
+        if [ -n "$FIREBASE_KEYS_PROD" ]; then
+          echo "FIREBASE_KEYS_PROD is set."
+        else
+          echo "Error: FIREBASE_KEYS_PROD is not set." >&2
+          exit 1
+        fi
 
   spell-check:
     uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
